/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/Modelos3D/Banca.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Banca(props) {
  const { nodes, materials } = useGLTF('./Modelos3D/Banca.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat20} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat23} />
    </group>
  )
}

useGLTF.preload('.Modelos3D/Banca.glb')
