/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/Modelos3D/Building2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Building2(props) {
  const { nodes, materials } = useGLTF('./Modelos3D/Building2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.large_buildingA_1.geometry} material={materials.border} />
      <mesh geometry={nodes.large_buildingA_1_1.geometry} material={materials._defaultMat} />
      <mesh geometry={nodes.large_buildingA_1_2.geometry} material={materials.window} />
      <mesh geometry={nodes.large_buildingA_1_3.geometry} material={materials.door} />
    </group>
  )
}

useGLTF.preload('./Modelos3D/Building2.glb')
