/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/Modelos3D/cuartoIndividualLegoRoom.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function LegoRoom(props) {
  const { nodes, materials } = useGLTF('./Modelos3D/cuartoIndividualLegoRoom.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.994, 0.885, -2.375]} rotation={[0, -Math.PI / 2, 0]} scale={4.666}>
        <group position={[0.034, 0, -0.036]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.OfficeChair_1.geometry} material={materials.Grey} />
          <mesh geometry={nodes.OfficeChair_2.geometry} material={materials.Black} />
          <mesh geometry={nodes.OfficeChair_3.geometry} material={materials.Chair} />
        </group>
      </group>
      <group position={[-5.326, 0.885, -2.375]} rotation={[0, -Math.PI / 2, 0]} scale={4.666}>
        <group position={[0.034, 0, -0.467]} rotation={[-Math.PI / 2, 0, 3.128]} scale={100}>
          <mesh geometry={nodes.OfficeChair002_1.geometry} material={materials['Grey.002']} />
          <mesh geometry={nodes.OfficeChair002_2.geometry} material={materials['Black.002']} />
          <mesh geometry={nodes.OfficeChair002_3.geometry} material={materials['Chair.002']} />
        </group>
      </group>
      <group position={[-5.326, 0.885, 1.703]} rotation={[0, -Math.PI / 2, 0]} scale={4.666}>
        <group position={[0.034, 0, -0.467]} rotation={[-Math.PI / 2, 0, 3.128]} scale={100}>
          <mesh geometry={nodes.OfficeChair003_1.geometry} material={materials['Grey.003']} />
          <mesh geometry={nodes.OfficeChair003_2.geometry} material={materials['Black.003']} />
          <mesh geometry={nodes.OfficeChair003_3.geometry} material={materials['Chair.003']} />
        </group>
      </group>
      <group position={[1.994, 0.885, 1.993]} rotation={[0, -Math.PI / 2, 0]} scale={4.666}>
        <group position={[0, 0, -0.036]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
          <mesh geometry={nodes.OfficeChair001_1.geometry} material={materials['Grey.001']} />
          <mesh geometry={nodes.OfficeChair001_2.geometry} material={materials['Black.001']} />
          <mesh geometry={nodes.OfficeChair001_3.geometry} material={materials['Chair.001']} />
        </group>
      </group>
      <group position={[0, 0.285, 0]} scale={[10, 0.1, 12]}>
        <mesh geometry={nodes.Cube.geometry} material={materials.LegoRoom} />
        <mesh geometry={nodes.Cube_1.geometry} material={materials.Suelo1} />
        <mesh geometry={nodes.Cube_2.geometry} material={materials.Suelo2} />
        <mesh geometry={nodes.Cube_3.geometry} material={materials.MarcoVentana} />
        <mesh geometry={nodes.Cube_4.geometry} material={materials.Techo} />
      </group>
      <mesh geometry={nodes.Ventana.geometry} material={materials.Ventana} position={[9.679, 6.181, -0.468]} scale={[0.05, 2.5, 6.85]} />
      <mesh geometry={nodes.texto_LegoRoom.geometry} material={materials.Letras} position={[7.692, 1.295, -11.6]} rotation={[Math.PI / 2, 0, Math.PI]} scale={[2.5, 1, 2.5]} />
      <mesh geometry={nodes.Mesa.geometry} material={materials.Mesa} position={[-0.46, 4.102, -0.31]} scale={[3, 0.15, 5]} />
      <group position={[-5.483, 4.78, 9.917]} rotation={[0, Math.PI / 2, 0]} scale={5.724}>
        <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat22} />
        <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat21} />
      </group>
      <mesh geometry={nodes.PizarronDeCorcho.geometry} material={materials.Mat} position={[3.226, 3.936, 10.337]} rotation={[0, Math.PI / 2, 0]} scale={0.054} />
      <group position={[-1.097, 4.277, 1.962]} rotation={[0, -1.57, 0]} scale={0.007}>
        <mesh geometry={nodes.System_unit_1.geometry} material={materials.lambert3SG} />
        <mesh geometry={nodes.System_unit_1_1.geometry} material={materials.initialShadingGroup} />
      </group>
      <mesh geometry={nodes.Comp_Mouse.geometry} material={materials.lambert3SG} position={[-1.097, 4.277, 1.962]} rotation={[0, -1.57, 0]} scale={0.007} />
      <mesh geometry={nodes.Drive.geometry} material={materials.lambert3SG} position={[-1.097, 4.277, 1.962]} rotation={[0, -1.57, 0]} scale={0.007} />
      <mesh geometry={nodes.Keyboard1.geometry} material={materials.lambert3SG} position={[-1.097, 4.277, 1.962]} rotation={[0, -1.57, 0]} scale={0.007} />
      <mesh geometry={nodes.Monitor.geometry} material={materials.lambert3SG} position={[-1.097, 4.277, 1.962]} rotation={[0, -1.57, 0]} scale={0.007} />
      <group position={[0.399, 4.277, -2.261]} rotation={[0, 1.567, 0]} scale={0.007}>
        <mesh geometry={nodes.System_unit_1001.geometry} material={materials['lambert3SG.001']} />
        <mesh geometry={nodes.System_unit_1001_1.geometry} material={materials['initialShadingGroup.001']} />
      </group>
      <mesh geometry={nodes.Monitor001.geometry} material={materials['lambert3SG.001']} position={[0.399, 4.277, -2.261]} rotation={[0, 1.567, 0]} scale={0.007} />
      <mesh geometry={nodes.Keyboard1001.geometry} material={materials['lambert3SG.001']} position={[0.399, 4.277, -2.261]} rotation={[0, 1.567, 0]} scale={0.007} />
      <mesh geometry={nodes.Drive001.geometry} material={materials['lambert3SG.001']} position={[0.399, 4.277, -2.261]} rotation={[0, 1.567, 0]} scale={0.007} />
      <mesh geometry={nodes.Comp_Mouse001.geometry} material={materials['lambert3SG.001']} position={[0.399, 4.277, -2.261]} rotation={[0, 1.567, 0]} scale={0.007} />
    </group>
  )
}

useGLTF.preload('./Modelos3D/cuartoIndividualLegoRoom.glb')
