/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/Modelos3D/EdificioDREAM.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function EdificioDREAM(props) {
  const { nodes, materials } = useGLTF('./Modelos3D/EdificioDREAM.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Base.geometry} material={materials['Material.001']} position={[0, -5.437, 0]} scale={[300, 1, 300]} />
      <mesh geometry={nodes.Base_edificio.geometry} material={nodes.Base_edificio.material} position={[0, 4, 0]} scale={[250, 1, 250]} />
      <mesh geometry={nodes.Pilar01.geometry} material={nodes.Pilar01.material} position={[120, 79.5, 120]} scale={[1, 15, 1]} />
      <mesh geometry={nodes.Pilar02.geometry} material={nodes.Pilar02.material} position={[120, 79.5, -120]} scale={[1, 15, 1]} />
      <mesh geometry={nodes.Pilar03.geometry} material={nodes.Pilar03.material} position={[-120, 79, -120]} scale={[1, 15, 1]} />
      <mesh geometry={nodes.Pilar04.geometry} material={nodes.Pilar04.material} position={[-120, 79, 120]} scale={[1, 15, 1]} />
      <group position={[113.75, 79.5, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials['Cuadros ventanas']} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.ventana} />
      </group>
      <group position={[-113.75, 79, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube007.geometry} material={materials['Cuadros ventanas']} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials.ventana} />
      </group>
      <group position={[0, 79.5, 113.75]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube008.geometry} material={materials['Cuadros ventanas']} />
        <mesh geometry={nodes.Cube008_1.geometry} material={materials.ventana} />
      </group>
      <group position={[0, 79.5, -116.25]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['Cuadros ventanas.002']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['ventana.002']} />
      </group>
      <mesh geometry={nodes.Techo1.geometry} material={nodes.Techo1.material} position={[0, 153.5, 0]} scale={[250, 1, 250]} />
      <group position={[113.75, 229.5, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube014.geometry} material={materials['Cuadros ventanas.006']} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials['ventana.006']} />
      </group>
      <group position={[-113.75, 229, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube013.geometry} material={materials['Cuadros ventanas.005']} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['ventana.005']} />
      </group>
      <group position={[0, 229.5, 116.25]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube012.geometry} material={materials['Cuadros ventanas.004']} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials['ventana.004']} />
      </group>
      <group position={[0, 229.5, -116.25]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials['Cuadros ventanas.003']} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials['ventana.003']} />
      </group>
      <mesh geometry={nodes.Techo1001.geometry} material={nodes.Techo1001.material} position={[0, 303.17, 0]} scale={[250, 1, 250]} />
      <group position={[113.75, 379.17, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['Cuadros ventanas.006']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['ventana.006']} />
      </group>
      <group position={[-113.75, 378.67, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials['Cuadros ventanas.005']} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['ventana.005']} />
      </group>
      <group position={[0, 379.17, 116.25]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials['Cuadros ventanas.004']} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials['ventana.004']} />
      </group>
      <group position={[0, 379.17, -116.25]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube016.geometry} material={materials['Cuadros ventanas.003']} />
        <mesh geometry={nodes.Cube016_1.geometry} material={materials['ventana.003']} />
      </group>
      <mesh geometry={nodes.Techo1002.geometry} material={nodes.Techo1002.material} position={[0, 453.295, 0]} scale={[250, 1, 250]} />
      <group position={[113.75, 529.295, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube017.geometry} material={materials['Cuadros ventanas.006']} />
        <mesh geometry={nodes.Cube017_1.geometry} material={materials['ventana.006']} />
      </group>
      <group position={[-113.75, 528.795, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube018.geometry} material={materials['Cuadros ventanas.005']} />
        <mesh geometry={nodes.Cube018_1.geometry} material={materials['ventana.005']} />
      </group>
      <group position={[0, 529.295, 116.25]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube019.geometry} material={materials['Cuadros ventanas.004']} />
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['ventana.004']} />
      </group>
      <group position={[0, 529.295, -116.25]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube020.geometry} material={materials['Cuadros ventanas.003']} />
        <mesh geometry={nodes.Cube020_1.geometry} material={materials['ventana.003']} />
      </group>
      <mesh geometry={nodes.Techo1003.geometry} material={nodes.Techo1003.material} position={[0, 602.733, 0]} scale={[250, 1, 250]} />
      <mesh geometry={nodes.dreamLab.geometry} material={materials.Material} position={[-90.292, 613.46, 136.055]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.dreamLab001.geometry} material={materials['Material.002']} position={[137.5, 613.46, 90.074]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dreamLab002.geometry} material={materials['Material.003']} position={[90.272, 613.46, -137.5]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.dreamLab003.geometry} material={materials['Material.004']} position={[-137.5, 613.46, -87.745]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
    </group>
  )
}

useGLTF.preload('./Modelos3D/EdificioDREAM.glb')
