/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/Modelos3D/Floor2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Floor2(props) {
  const { nodes, materials } = useGLTF('./Modelos3D/Floor2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.floor_dirt.geometry} material={materials.HalloweenBits} scale={100} />
    </group>
  )
}

useGLTF.preload('./Modelos3D/Floor2.glb')
