/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/Modelos3D/Floor.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Floor(props) {
  const { nodes, materials } = useGLTF('./Modelos3D/Floor.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Floor_Modular.geometry} material={materials.Grey_Floor} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('./Modelos3D/Floor.glb')
