/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/Modelos3D/lampara.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Lampara(props) {
  const { nodes, materials } = useGLTF('./Modelos3D/lampara.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.lambert4SG} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.lambert2SG} />
      <mesh geometry={nodes['Node-Mesh_2'].geometry} material={materials.lambert3SG} />
    </group>
  )
}

useGLTF.preload('./Modelos3D/lampara.glb')
