/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/Modelos3D/Marker.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Marker(props) {
  const { nodes, materials } = useGLTF('./Modelos3D/Marker.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat8} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat23} />
    </group>
  )
}

useGLTF.preload('./Modelos3D/Marker.glb')
