/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/Modelos3D/ModelosEdificiosDREAM.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function  ModelosEdificiosDREAM(props) {
  const { nodes, materials } = useGLTF('./Modelos3D/ModelosEdificiosDREAM.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.dreamLab.geometry} material={materials.Material} position={[-90.292, 613.46, 136.055]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.dreamLab001.geometry} material={materials['Material.002']} position={[137.5, 613.46, 90.074]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} />
      <mesh geometry={nodes.dreamLab002.geometry} material={materials['Material.003']} position={[90.272, 613.46, -137.5]} rotation={[Math.PI / 2, 0, Math.PI]} />
      <mesh geometry={nodes.dreamLab003.geometry} material={materials['Material.004']} position={[-137.5, 613.46, -87.745]} rotation={[Math.PI / 2, 0, Math.PI / 2]} />
      <mesh geometry={nodes.Techo1002.geometry} material={materials.dreamColor} position={[0, 453.295, 0]} scale={[250, 1, 250]} />
      <group position={[113.75, 529.295, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube017.geometry} material={materials['Cuadros ventanas.006']} />
        <mesh geometry={nodes.Cube017_1.geometry} material={materials['ventana.006']} />
      </group>
      <group position={[-113.75, 528.795, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube018.geometry} material={materials['Cuadros ventanas.005']} />
        <mesh geometry={nodes.Cube018_1.geometry} material={materials['ventana.005']} />
      </group>
      <group position={[0, 529.295, 116.25]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube019.geometry} material={materials['Cuadros ventanas.004']} />
        <mesh geometry={nodes.Cube019_1.geometry} material={materials['ventana.004']} />
      </group>
      <group position={[0, 529.295, -116.25]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube020.geometry} material={materials['Cuadros ventanas.003']} />
        <mesh geometry={nodes.Cube020_1.geometry} material={materials['ventana.003']} />
      </group>
      <mesh geometry={nodes.Techo1003.geometry} material={materials.dreamColor} position={[0, 602.733, 0]} scale={[250, 1, 250]} />
      <mesh geometry={nodes.Techo1001.geometry} material={materials.dreamColor} position={[0, 303.17, 0]} scale={[250, 1, 250]} />
      <group position={[113.75, 379.17, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube005.geometry} material={materials['Cuadros ventanas.006']} />
        <mesh geometry={nodes.Cube005_1.geometry} material={materials['ventana.006']} />
      </group>
      <group position={[-113.75, 378.67, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube009.geometry} material={materials['Cuadros ventanas.005']} />
        <mesh geometry={nodes.Cube009_1.geometry} material={materials['ventana.005']} />
      </group>
      <group position={[0, 379.17, 116.25]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube015.geometry} material={materials['Cuadros ventanas.004']} />
        <mesh geometry={nodes.Cube015_1.geometry} material={materials['ventana.004']} />
      </group>
      <group position={[0, 379.17, -116.25]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube016.geometry} material={materials['Cuadros ventanas.003']} />
        <mesh geometry={nodes.Cube016_1.geometry} material={materials['ventana.003']} />
        <mesh geometry={nodes.Cube016_2.geometry} material={materials.Puertas} />
      </group>
      <mesh geometry={nodes.Techo1.geometry} material={materials.dreamColor} position={[0, 153.5, 0]} scale={[250, 1, 250]} />
      <group position={[113.75, 229.5, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube014.geometry} material={materials['Cuadros ventanas.006']} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials['ventana.006']} />
      </group>
      <group position={[-113.75, 229, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube013.geometry} material={materials['Cuadros ventanas.005']} />
        <mesh geometry={nodes.Cube013_1.geometry} material={materials['ventana.005']} />
      </group>
      <group position={[0, 229.5, 116.25]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube012.geometry} material={materials['Cuadros ventanas.004']} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials['ventana.004']} />
      </group>
      <group position={[0, 229.5, -116.25]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials['Cuadros ventanas.003']} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials['ventana.003']} />
        <mesh geometry={nodes.Cube011_2.geometry} material={materials.Puertas} />
      </group>
      <mesh geometry={nodes.Base.geometry} material={materials['Material.001']} position={[0, -1.389, 0]} scale={[300, 1, 300]} />
      <mesh geometry={nodes.Base_edificio.geometry} material={materials.dreamColor} position={[0, 4, 0]} scale={[250, 1, 250]} />
      <mesh geometry={nodes.Pilar01.geometry} material={materials.dreamColor} position={[120, 79.5, 120]} scale={[1, 15, 1]} />
      <mesh geometry={nodes.Pilar02.geometry} material={materials.dreamColor} position={[120, 79.5, -120]} scale={[1, 15, 1]} />
      <mesh geometry={nodes.Pilar03.geometry} material={materials.dreamColor} position={[-120, 79, -120]} scale={[1, 15, 1]} />
      <mesh geometry={nodes.Pilar04.geometry} material={materials.dreamColor} position={[-120, 79, 120]} scale={[1, 15, 1]} />
      <group position={[113.75, 79.5, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube006.geometry} material={materials['Cuadros ventanas']} />
        <mesh geometry={nodes.Cube006_1.geometry} material={materials.ventana} />
        <mesh geometry={nodes.Cube006_2.geometry} material={materials.Puertas} />
      </group>
      <group position={[-113.75, 79, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube007.geometry} material={materials['Cuadros ventanas']} />
        <mesh geometry={nodes.Cube007_1.geometry} material={materials.ventana} />
      </group>
      <group position={[0, 79.5, 113.75]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube008.geometry} material={materials['Cuadros ventanas']} />
        <mesh geometry={nodes.Cube008_1.geometry} material={materials.ventana} />
        <mesh geometry={nodes.Cube008_2.geometry} material={materials.Puertas} />
      </group>
      <group position={[0, 79.5, -116.25]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube010.geometry} material={materials['Cuadros ventanas.002']} />
        <mesh geometry={nodes.Cube010_1.geometry} material={materials['ventana.002']} />
        <mesh geometry={nodes.Cube010_2.geometry} material={materials.Puertas} />
      </group>
      <mesh geometry={nodes.Base001.geometry} material={materials['Material.009']} position={[0, -1.389, -299.618]} scale={[300, 1, 300]} />
      <mesh geometry={nodes.Base_edificio001.geometry} material={materials['dreamColor.001']} position={[0, 4, -249.643]} scale={[250, 1, 250]} />
      <mesh geometry={nodes.Pilar02001.geometry} material={materials['dreamColor.002']} position={[120, 79.5, -420.643]} scale={[1, 15, 1]} />
      <mesh geometry={nodes.Pilar02002.geometry} material={materials['dreamColor.003']} position={[-120, 79.5, -420.643]} scale={[1, 15, 1]} />
      <mesh geometry={nodes.Base_edificio002.geometry} material={materials['dreamColor.004']} position={[0, 157.5, -249.643]} scale={[250, 1, 250]} />
      <mesh geometry={nodes.Base_edificio003.geometry} material={materials['dreamColor.005']} position={[0, 307.17, -249.643]} scale={[250, 1, 250]} />
      <group position={[0, 229.5, -418.127]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube023.geometry} material={materials['Cuadros ventanas.001']} />
        <mesh geometry={nodes.Cube023_1.geometry} material={materials['ventana.001']} />
      </group>
      <group position={[0, 79.5, -418.127]} rotation={[0, Math.PI / 2, 0]} scale={[0.25, 15, 23]}>
        <mesh geometry={nodes.Cube024.geometry} material={materials['Cuadros ventanas.007']} />
        <mesh geometry={nodes.Cube024_1.geometry} material={materials['ventana.007']} />
        <mesh geometry={nodes.Cube024_2.geometry} material={materials.Puertas} />
      </group>
      <group position={[113.75, 229.5, -270.543]} rotation={[Math.PI, 0, Math.PI]} scale={[0.25, 15, 29.363]}>
        <mesh geometry={nodes.Cube025.geometry} material={materials['Cuadros ventanas.008']} />
        <mesh geometry={nodes.Cube025_1.geometry} material={materials['ventana.008']} />
      </group>
      <group position={[113.75, 79.5, -270.543]} scale={[0.25, 15, 29.363]}>
        <mesh geometry={nodes.Cube026.geometry} material={materials['Cuadros ventanas.009']} />
        <mesh geometry={nodes.Cube026_1.geometry} material={materials['ventana.009']} />
      </group>
      <group position={[-117.5, 229.5, -270.543]} scale={[0.25, 15, 29.363]}>
        <mesh geometry={nodes.Cube027.geometry} material={materials['Cuadros ventanas.010']} />
        <mesh geometry={nodes.Cube027_1.geometry} material={materials['ventana.010']} />
      </group>
      <group position={[-117.5, 79.5, -270.543]} scale={[0.25, 15, 29.363]}>
        <mesh geometry={nodes.Cube028.geometry} material={materials['Cuadros ventanas.011']} />
        <mesh geometry={nodes.Cube028_1.geometry} material={materials['ventana.011']} />
      </group>
      <mesh geometry={nodes.Table_Small_Rectangular_01_Circle008.geometry} material={materials['795548']} position={[65.538, 307.67, -369.356]} scale={1.725} />
      <mesh geometry={nodes.Table_Small_Rectangular_01_Circle001.geometry} material={materials['795548.001']} position={[-55.543, 307.67, -369.356]} scale={1.725} />
      <mesh geometry={nodes.Table_Small_Rectangular_01_Circle002.geometry} material={materials['795548.002']} position={[8.3, 307.67, -317.293]} scale={1.725} />
      <mesh geometry={nodes.Table_Small_Rectangular_01_Circle003.geometry} material={materials['795548.003']} position={[88.195, 307.67, -257.812]} scale={1.725} />
      <mesh geometry={nodes.Table_Small_Rectangular_01_Circle004.geometry} material={materials['795548.004']} position={[-70.824, 307.67, -210.894]} scale={1.725} />
    </group>
  )
}

useGLTF.preload('./Modelos3D/ModelosEdificiosDREAM.glb')
