/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/Modelos3D/plan.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Plan(props) {
  const { nodes, materials } = useGLTF('./Modelos3D/plan.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh2_Group1_Model.geometry} material={materials.______________01} />
      <mesh geometry={nodes.Mesh3_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh4_Group1_Model.geometry} material={materials._________________} />
      <mesh geometry={nodes.Mesh5_Group1_Model.geometry} material={materials.__________________________} />
      <mesh geometry={nodes.Mesh6_Group1_Model.geometry} material={materials.__________________________} />
      <mesh geometry={nodes.Mesh7_Group1_Model.geometry} material={materials.__________________________} />
      <mesh geometry={nodes.Mesh8_Group1_Model.geometry} material={materials.__________________________} />
      <mesh geometry={nodes.Mesh10_Group1_Model.geometry} material={materials.______________________} />
      <mesh geometry={nodes.Mesh11_Group1_Model.geometry} material={materials._____________________} />
      <mesh geometry={nodes.Mesh12_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh13_Group1_Model.geometry} material={materials._________________________} />
      <mesh geometry={nodes.Mesh14_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh15_Group1_Model.geometry} material={materials._____________________} />
      <mesh geometry={nodes.Mesh16_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh17_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh18_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh19_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh20_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh21_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh23_Group1_Model.geometry} material={materials._____________________} />
      <mesh geometry={nodes.Mesh24_Group1_Model.geometry} material={materials._____________________} />
      <mesh geometry={nodes.Mesh25_Group1_Model.geometry} material={materials._____________________} />
      <mesh geometry={nodes.Mesh26_Group1_Model.geometry} material={materials._____________________} />
      <mesh geometry={nodes.Mesh27_Group1_Model.geometry} material={materials.__________________________} />
      <mesh geometry={nodes.Mesh28_Group1_Model.geometry} material={materials.__________________________} />
      <mesh geometry={nodes.Mesh29_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh30_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh31_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh33_Group1_Model.geometry} material={materials._____________________} />
      <mesh geometry={nodes.Mesh34_Group1_Model.geometry} material={materials._____________________} />
      <mesh geometry={nodes.Mesh35_Group1_Model.geometry} material={materials._____________________} />
      <mesh geometry={nodes.Mesh36_Group1_Model.geometry} material={materials._____________________} />
      <mesh geometry={nodes.Mesh37_Group1_Model.geometry} material={materials._____________________} />
      <mesh geometry={nodes.Mesh38_Group1_Model.geometry} material={materials._____________________} />
      <mesh geometry={nodes.Mesh39_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh40_Group1_Model.geometry} material={materials.________________________________________} />
      <mesh geometry={nodes.Mesh41_Group1_Model.geometry} material={materials.________________________________________} />
      <mesh geometry={nodes.Mesh42_Group1_Model.geometry} material={materials.______________________} />
      <mesh geometry={nodes.Mesh43_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh44_Group1_Model.geometry} material={materials.__________________________} />
      <mesh geometry={nodes.Mesh45_Group1_Model.geometry} material={materials.__________________________} />
      <mesh geometry={nodes.Mesh47_Group1_Model.geometry} material={materials._________________________} />
      <mesh geometry={nodes.Mesh48_Group1_Model.geometry} material={materials._________________________} />
      <mesh geometry={nodes.Mesh49_Group1_Model.geometry} material={materials.______________01} />
      <mesh geometry={nodes.Mesh50_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh51_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh52_Group1_Model.geometry} material={materials.__________________________} />
      <mesh geometry={nodes.Mesh54_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh55_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh56_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh57_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh58_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh59_Group1_Model.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1.geometry} material={materials._________________________} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_1.geometry} material={materials.________________________________________} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_2.geometry} material={materials.___________________________} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_3.geometry} material={materials.________________01} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_4.geometry} material={materials.___________________________2_} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_5.geometry} material={materials.________02} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_6.geometry} material={materials.___________________________1_} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_7.geometry} material={materials.Concrete_Scored_Jointless} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_8.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_9.geometry} material={materials._________________} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_10.geometry} material={materials._________________1_} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_11.geometry} material={materials.__________________________} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_12.geometry} material={materials.________04} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_13.geometry} material={materials.______________________________________} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_14.geometry} material={materials.____________________} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_15.geometry} material={materials._________________2_} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_16.geometry} material={materials._____________________} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_17.geometry} material={materials.______________01} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_18.geometry} material={materials._________________3_} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_19.geometry} material={materials._______________} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_20.geometry} material={materials._____________} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_21.geometry} material={materials.________01} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_22.geometry} material={materials.________________________} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_23.geometry} material={materials.________________} />
      <mesh geometry={nodes.Mesh1_Group1_Model_1_24.geometry} material={materials.GDLM11_pictmat} />
      <mesh geometry={nodes.Mesh9_Group1_Model_1.geometry} material={materials._________________________} />
      <mesh geometry={nodes.Mesh9_Group1_Model_1_1.geometry} material={materials.________________} />
      <mesh geometry={nodes.Mesh22_Group1_Model_1.geometry} material={materials.______________________________} />
      <mesh geometry={nodes.Mesh22_Group1_Model_1_1.geometry} material={materials.______________________} />
      <mesh geometry={nodes.Mesh32_Group1_Model_1.geometry} material={materials.________________} />
      <mesh geometry={nodes.Mesh32_Group1_Model_1_1.geometry} material={materials._________________________} />
      <mesh geometry={nodes.Mesh46_Group1_Model_1.geometry} material={materials.________02} />
      <mesh geometry={nodes.Mesh46_Group1_Model_1_1.geometry} material={materials._________________________} />
      <mesh geometry={nodes.Mesh53_Group1_Model_1.geometry} material={materials.______________________} />
      <mesh geometry={nodes.Mesh53_Group1_Model_1_1.geometry} material={materials.______________________________} />
    </group>
  )
}

useGLTF.preload('./Modelos3D/plan.glb')
